server:
  port: 8082
  servlet:
    context-path: /api

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  level:
    root: info
    com:
      org:
        example: debug
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

remote:
  user-service:
    url: http://localhost:8081/api/
rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem