spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0